### ISSUE TITLE
Change logged user

### ISSUE THREAD

**Issue by gianlucainnocente** [ConnectyCube/connectycube-flutter-sdk-releases#10]
**Specify the sample to which the issue belongs (use [x]):**
[ X] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[X ] Android
[X ] iOS

**Device info**
Manufacture: Apple
Model: iPhone 11
OS version: 13.6.1

**Describe the bug:**
If i start the app and login with a user, videocall works perfectly.
But if i change the user, the session starts but i can't receive calls.

**Comment by TatankaConCube** [comment]
@gianlucainnocente, thank you for reporting, we will investigate this issue

**Comment by TatankaConCube** [comment]
we localized problem, we will fix it in next release

**Comment by TatankaConCube** [comment]
@gianlucainnocente today we released version [0.4.1](https://pub.dev/packages/connectycube_sdk/versions/0.4.1) with required fixes. Please check and close this ticket if your issue resolved.

**Comment by TatankaConCube** [comment]
Similar issues were resolved in the latest versions. Closing.
