### ISSUE TITLE
How to access CubeAttachmentType.AUDIO file data

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [ConnectyCube/connectycube-flutter-sdk-releases#100]
**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
N/A

**Describe the bug:**
I have no clue on how to access audio data for an Audio type attachment. I cant find any documentation as to how this media type can be properly fetched and the data initialised as a audio media for audio players

**Steps to Reproduce:**
1. Upload a CubeAttachment.AUDIO type file to a dialog
2. Get cube messages for a dialog

**Logs:**
```
I/flutter ( 5907):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 2.11.1, CB-Token: FF1618F7E46242B2E9E5464E4BBD79121C49}
I/flutter ( 5907): BODY
I/flutter ( 5907):   
I/flutter ( 5907): 
D/EGL_emulation( 5907): app_time_stats: avg=38.05ms min=0.78ms max=419.61ms count=22
D/EGL_emulation( 5907): app_time_stats: avg=17.22ms min=4.36ms max=63.23ms count=54
I/flutter ( 5907): CB-SDK: : *********************************************************
I/flutter ( 5907): *** RESPONSE *** 200 *** c8adde01-e1df-4918-a4e0-1b584df7b825 ***
I/flutter ( 5907): HEADERS
I/flutter ( 5907):   {cb-token-expirationdate: 2023-12-10 14:41:01 UTC, connection: keep-alive, date: Sun, 10 Dec 2023 12:41:01 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 2387, access-control-expose-headers: CB-Token-ExpirationDate, Date, content-type: application/json; charset=utf-8, server: nginx/1.25.0}
I/flutter ( 5907): BODY
I/flutter ( 5907):   {"skip":0,"limit":100,"items":[{"_id":"6575af535c696e97045fa50b","chat_dialog_id":"64a7f5a70f93a0002f855622","message":"Attachment","date_sent":1702211412,"sender_id":8633139,"recipient_id":8633117,"created_at":"2023-12-10T12:30:12Z","updated_at":"2023-12-10T12:30:12Z","read_ids":[8633139],"delivered_ids":[8633139],"attachments":[{"type":"audio","uid":"627C6F1783505AB1EBB91EF2B542809DEB67"}],"reactions":null,"views_count":0,"edited_at":null,"read":0},{"_id":"6575ace95c696e97045fa509","chat_dialog_id":"64a7f5a70f93a0002f855622","message":"what is this?","date_sent":1702210793,"sender_id":8633139,"recipient_id":8633117,"created_at":"2023-12-10T12:19:54Z","updated_at":"2023-12-10T12:19:54Z","read_ids":[8633139],"delivered_ids":[8633139],"reactions":null,"views_count":0,"attachments":[],"edited_at":null,"read":0},{"_id":"6575a8485c696e97045fa508","chat_dialog_id":"64a7f5a70f93a0002f855622","message":"Attachment","date_sent":1702209609,"sender_id":8633139,"recipient_id":8633117,"created_at":"2023-12-10T12:00:10

Specifically the audio type attachment:
[{id: null, uid: 627Cxxxxxxxxxx9xxx542xxEBxx, type: audio, url: null, content-type: null, size: null, name: null, data: null, width: null, height: null, duration: null}]
```

**Actual result:**
Cannot obtain data for an Audio attachment type

**Expected behavior:**
Obtain audio file data from the cube message

**Additional info**
Please add example documentation on uploading, downloading and initialising Audio type data.
The Cube admin dashboard shows the files as being uploaded, however the response data for this specific message shows as 'null'
<img width="837" alt="image" src="https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/assets/53292031/0daf79e5-ad44-4d77-9f8e-c0ddc6909eda">

**Comment by TatankaConCube** [comment]
The main logic for uploading/downloading/displaying all types of attachments is similar. The difference is only for displaying your attachment on the UI. In your case you upload the audio as a private file, so you should use the `getPrivateUrlForUid(uid);` function to get the URL on your uploaded file.

We have plans to add audio/video/location types of attachments in our Chat sample but we don't have the end date of implementation of these features.

**Comment by TatankaConCube** [comment]
I'm not sure that it is useful for all users, because every developer uses their own preferred tools for working with a network

**Comment by TatankaConCube** [comment]
have you tried any other libs for displaying audio waves? looks like this [flutter_audio_waveforms](https://pub.dev/packages/flutter_audio_waveforms) has required functionality and supports the URL type of path

**Comment by AbdurrehmanSubhani** [comment]
> have you tried any other libs for displaying audio waves? looks like this [flutter_audio_waveforms](https://pub.dev/packages/flutter_audio_waveforms) has required functionality and supports the URL type of path

No i haven't given this package a shot yet, also im kind of constrained with the audio_waveforms as its being used with the [chatview](https://pub.dev/packages/chatviewl) package, unless i fork and try to change the underlying audio player in this package.
I tried the chatview package for a quick chat app build and it provides some great out of the box features, and so i only got limited by not being able to play the audio file on the opponent's side, which hopefully will be solved by downloading through the private url.

**Comment by TatankaConCube** [comment]
ok, understood, thank you for your reply
