### ISSUE TITLE
loggin/signin takes 5 to 10 seconds

### ISSUE THREAD

**Issue by rdhillbb** [ConnectyCube/connectycube-flutter-sdk-releases#12]
**Platform (use [x])**
[ x] Android
[ ] iOS

**Device info**
Manufacture: Oppo
Model: [CPH2083]
OS version: [Android 10]

It takes 5 to 10 seconds to log in to connectyCube. Is this normal?
Is this expected behavior?

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
hello @rdhillbb, now I did internal tests and got nex values:

REST (create a session with user):
CB-SDK: : start REST login 2020-09-23 18:43:49.740228
CB-SDK: : end REST login 2020-09-23 18:43:51.142763

Login to the chat:
CB-SDK: : start CHAT login 2020-09-23 18:43:51.146645
CB-SDK: : end CHAT login 2020-09-23 18:43:53.869167

Do you have similar values?

**Comment by rdhillbb** [comment]
Here are my latest results
6271 ms 6.271 seconds
4886 ms 4.886 seconds
5749 ms  5.749 seconds
The code snippets show how I measure the time. It is based off of the sample app.
The sample app has similar behavior.  


void _loginToCubeChat(CubeUser user) {
 stimer.start();
 CubeChatConnection.instance.login(user).then((cubeUser) {
 stimer.stop();
 InitCallHeyDoc();
 Flushbar(
 title: "HeyDoc Notification",
 message: "Login completed ${stimer.elapsedMilliseconds}",
 duration: Duration(seconds: 3),
 )..show(clientContext);
 }).catchError(_processLoginError);
}


void InitCallHeyDoc() {
 _initCallsHeyDoc();
}


void _initCallsHeyDoc() {
 _callClient = P2PClient.instance;


 _callClient.init();


 _callClient.onReceiveNewSession = (callSession) {
 if (_currentCall != null &&
 _currentCall.sessionId != callSession.sessionId) {
 callSession.reject();
 return;
 }


 _showIncomingCallScreen(callSession);
 };


 _callClient.onSessionClosed = (callSession) {
 if (_currentCall != null &&
 _currentCall.sessionId == callSession.sessionId) {
 _currentCall = null;
 }
 };
}







On September 23, 2020 at 11:50 PM, TatankaConCube <notifications@github.com> wrote:






hello @rdhillbb, now I did internal tests and got nex values:

REST (create a session with user):
CB-SDK: : start REST login 2020-09-23 18:43:49.740228
CB-SDK: : end REST login 2020-09-23 18:43:51.142763

Login to the chat:
CB-SDK: : start CHAT login 2020-09-23 18:43:51.146645
CB-SDK: : end CHAT login 2020-09-23 18:43:53.869167

Do you have similar values?

**Comment by rdhillbb** [comment]
Just to thorough, I am in Cambodia testing. 
On September 24, 2020 at 2:22 PM, Randolph Hill <rdhillbb@icloud.com> wrote:


Here are my latest results
6271 ms 6.271 seconds
4886 ms 4.886 seconds
5749 ms  5.749 seconds
The code snippets show how I measure the time. It is based off of the sample app.
The sample app has similar behavior.  


void _loginToCubeChat(CubeUser user) {
 stimer.start();
 CubeChatConnection.instance.login(user).then((cubeUser) {
 stimer.stop();
 InitCallHeyDoc();
 Flushbar(
 title: "HeyDoc Notification",
 message: "Login completed ${stimer.elapsedMilliseconds}",
 duration: Duration(seconds: 3),
 )..show(clientContext);
 }).catchError(_processLoginError);
}


void InitCallHeyDoc() {
_initCallsHeyDoc();
}


void _initCallsHeyDoc() {
_callClient = P2PClient.instance;


_callClient.init();


_callClient.onReceiveNewSession = (callSession) {
if (_currentCall != null &&
_currentCall.sessionId != callSession.sessionId) {
callSession.reject();
return;
}


_showIncomingCallScreen(callSession);
};


_callClient.onSessionClosed = (callSession) {
if (_currentCall != null &&
_currentCall.sessionId == callSession.sessionId) {
_currentCall = null;
}
};
}







On September 23, 2020 at 11:50 PM, TatankaConCube <notifications@github.com> wrote:






hello @rdhillbb, now I did internal tests and got nex values:

REST (create a session with user):
CB-SDK: : start REST login 2020-09-23 18:43:49.740228
CB-SDK: : end REST login 2020-09-23 18:43:51.142763

Login to the chat:
CB-SDK: : start CHAT login 2020-09-23 18:43:51.146645
CB-SDK: : end CHAT login 2020-09-23 18:43:53.869167

Do you have similar values?

**Comment by TatankaConCube** [comment]
I think 3-4 second it is expected duration of the chat connection process. But it depends on some additional factors, e.g. type of internet connection, internet connection speed, distance from the target server, etc.

**Comment by rdhillbb** [comment]
Thank you.
