### ISSUE TITLE
Incompatibility with flutter_svg

### ISSUE THREAD

**Issue by nomadcore** [ConnectyCube/connectycube-flutter-sdk-releases#14]
**Platform (use [x])**
[x] Android
[x] iOS

**Describe the bug:**
After update flutter to 1.22 flutter_svg min version is 1.18.0. As a result connectycube_sdk and flutter_svg conflicted due transitive xml dependency

**Steps to Reproduce:**
1. Just add  connectycube_sdk: 0.4.2 and flutter_svg: ^0.19.0 (or 0.18.0) to pubspec.yaml
2. Flutter pub get

**Logs:**
```
[my_application] flutter pub get
Running "flutter pub get" in my_application...        
Because connectycube_sdk 0.4.2 depends on xmpp_stone 0.2.7 which depends on xml ^3.2.5, connectycube_sdk 0.4.2 requires xml ^3.2.5.

And because flutter_svg >=0.18.1 depends on xml ^4.2.0, connectycube_sdk 0.4.2 is incompatible with flutter_svg >=0.18.1.

So, because my_application depends on both flutter_svg ^0.19.0 and connectycube_sdk 0.4.2, version solving failed.
pub get failed (1; So, because my_application depends on both flutter_svg ^0.19.0 and connectycube_sdk 0.4.2, version solving failed.)
exit code 1
```

**Actual result:**
Dependencies solving failed

**Expected behavior:**
Dependencies successfully solved

**Comment by TatankaConCube** [comment]
hello @nomadcore, thank you for your question, we will investigate, what we can do in this situation

**Comment by TatankaConCube** [comment]
we found the solution for this case and it will be fixed in the next release

**Comment by TatankaConCube** [comment]
@nomadcore today we updated our Flutter SDK to [0.5.0](https://pub.dev/packages/connectycube_sdk/versions/0.5.0). It contains fixes for your issue.

**Comment by nomadcore** [comment]
Thank you. Upgrade to flutter 1.22 successfully completed.
