### ISSUE TITLE
What is the correct order of API calls for connecting to ConnectyCube and some general questions

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-sdk-releases#16]
After many hours of trial and error, I managed to make my first successful API call to send a group message in Flutter. But I am not sure if I am doing things the right way. Unfortunatly the documentation does not help very much. It could be much less and much more informative imho. I would be very glad if someone can answer all of the questions here as the answers will be useful for many Connecty Cube beginners.

Right now the order I make my calls are as follows:
```
import 'package:connectycube_sdk/connectycube_chat.dart' as cc;
await cc.init(APP_ID, AUTH_KEY, AUTH_SECRET);
cubesession = await cc.createSession(); //create app session
//registeredUser = await cc.signUp(user); //if necessary
myuser = await cc.signInByLogin(userDocId, password);
cubeSession = await cc.createSession(myuser); //upgrade to user session
createdDialog = await cc.createDialog(newDialog); //is this for one time only? I can set the dialogId in the newDialog object but it is overwritten by a random uuid in the console. We should know what we can set and not clearly.
await cc.CubeChatConnection.instance.login(myuser); //login?? bad choice of a method mate. This starts the xmpp 2 way connection I guess.
subscribe and listen to cc.CubeChatConnection.instance.chatMessagesManager.chatMessagesStream
```
Tell me if above is the right way/order to call API methods.

Also how and in which order to release resources? CubeUser/CubeSession/CubeDialog/chatMessagesStream/CubeChatConnection

How can we set a custom property to a CubeUser? I want to pass my Firebase user doc id

How can we set a custom property to a CubeDialog? I want to pass my Firebase post doc id. I see there is a String name property but I want to use it for its real purpose.

How to join/leave a CubeDialog? (different than adding and removing an occupants) Do we always have to create a dialog? Or do we need to get the dialogs that we are in and somehow leave them?

An occupant should have the ability to leave a dialog without Admin removing them. How do we do this?

Why are the id's integers?

Why is there no void return types on the high level FLutter API?

Param arguments are not clear. They are just Map<String, String> objects so we don't know what key fields to put in them. For instance;

```
Future<PagedResult<CubeDialog>> getDialogs([Map<String, dynamic> params]) {
  return GetDialogsQuery(params).perform();
}
//What keys should I put in params to fully use pagination?
```

[This was posted in SO](https://stackoverflow.com/questions/64946158/what-is-the-correct-order-of-api-calls-for-connecting-to-connectycube-and-some-g)

**Comment by TatankaConCube** [comment]
hello @aytunch, thank you for your question.

> Tell me if above is the right way/order to call API methods.

yes, it is the right order to call ConnectyCube API (since version 1.0.0 you can skip this step `cubesession = await cc.createSession(); //create app session`

> Also how and in which order to release resources?

you can do this in any place where you don't need chat functions anymore

> How can we set a custom property to a CubeUser? I want to pass my Firebase user doc id

use field `cubeUser.customData` for it

> How can we set a custom property to a CubeDialog?

use field `cubeDialog.customData`, you can put there any needed data

> How to join/leave a CubeDialog?

adding and removing occupants is the right way to leave/join the dialog

> Do we always have to create a dialog? Or do we need to get the dialogs that we are in and somehow leave them?

no, you don't need to create dialog every time, you can just get updated dialog from the server via API

> An occupant should have the ability to leave a dialog without Admin removing them. How do we do this?

any user can remove their own id from occupants without admin privileges. It is possible via [update dialog](https://developers.connectycube.com/flutter/messaging?id=update-dialog) feature

> Why is there no void return types on the high level FLutter API?

which API do you mean?

> Param arguments are not clear.

you are right, we have to add more details for some API, we will do it soon
but before it, you can use our docs which describe our [Server's API](https://developers.connectycube.com/server/), [here](https://developers.connectycube.com/server/chat?id=retrieve-chat-dialogs) description for possible parameters for getting dialogs request

**Comment by aytunch** [comment]
Hi @TatankaConCube thanks for the answer,
you said 
> since version 1.0.0 you can skip this step cubesession = await cc.createSession(); //create app session

In this case, can we skip the `cubeSession = await cc.createSession(myuser); //upgrade to user session` too?

I checked the server API documentation as you suggested and found more info. However, I am not sure what Map key to use for getDialogs(params). I want to get a specific dialog with a certain dialogid. But I don't know the String key name. Can you please tell me? Right now I have it like this:
`await getDialogs({"_id": "abcd"});  //in the server api it says '_id' and JS api says 'chat_dialog_id'. What is it for Flutter?`

By the way can I use `sendMessage` to any arbitrary CubeDialog object by constructing like below. Is it ok to do this as long as my user is an occupant of that CubeDialog with the mygroupid? Do I need to set any other fields? Or do I have to everytime call getDialogs using mygroupid?
```
CubeDialog cubeDialog = CubeDialog(
      CubeDialogType.GROUP,
      dialogId: mygroupid,
    );

    await cubeDialog.sendMessage(message);
```

Some of your functions have no return type so they seem to be as dynamic and this makes things hard for us. Even if you made them as void, we would not see dynamic all around the place:)

**Comment by TatankaConCube** [comment]
> can we skip the cubeSession = await cc.createSession(myuser); //upgrade to user session too?

no, it is a required code for creating a user's session. In case when we can create a session without user, we do it on SDK side by ownself

> I want to get a specific dialog with a certain dialogid. 

your example is correct, you should orientate on Server API, I don't know, how JS SDK represent these parameters on its side.

> Do I need to set any other fields? Or do I have to everytime call getDialogs using mygroupid?

a better solution, in this case, will be saving dialogs somewhere in your app (DB), and before sending the message you can get it from this place and use it for sending messages. No, you don't need to call `getDialogs` if you don't need to get actual information about the dialog. For sending message your dialog model should contain `dialogId`, `type` and  `occupantsIds`

> Some of your functions have no return type so they seem to be as dynamic and this makes things hard for us. Even if you made them as void, we would not see dynamic all around the place:)

please provide an example of these API, and provide your vision of these API ))

**Comment by aytunch** [comment]
> a better solution, in this case, will be saving dialogs somewhere in your app (DB), and before sending the message you can get it from this place and use it for sending messages. No, you don't need to call getDialogs if you don't need to get actual information about the dialog. For sending message your dialog model should contain dialogId, type and occupantsIds

Why do we need to set `occupantsIds` for sending a message? Occupants might change during the lifetime of the dialog. I would rather not keep track of the occupants just to send a message. Can Inot  send a message to a dialog just by setting the dialogId and type?

**Comment by TatankaConCube** [comment]
sorry, one note, `occupantsIds` required only for type `CubeDialogType.PRIVATE` (it needs for evaluation opponent's id), for group dialog enough `dialogId` and `type`.

```dart
//this ooks like this in my code:
dynamic init(String applicationId, String authorizationKey, String authorizationSecret, {Future<CubeSession> Function() onSessionRestore})
```

can you please share the link to dart documentation with this recommendation?

**Comment by aytunch** [comment]
Hi,
I am getting an error while trying to use the sdk. It happens while I try to register a user:

> HEADERS
> I/flutter ( 9631):   {connection: keep-alive, set-cookie: _mkra_ctxt=5ba8a97b44cf66c7d44b4ec4d4e0b65d--422; path=/; max-age=5; HttpOnly; secure, cache-control: no-cache, status: 422 Unprocessable Entity, transfer-encoding: chunked, date: Tue, 24 Nov 2020 21:40:43 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: 8bf35e46-4dc3-4e74-baa8-9f13b681fcbd, connectycube-rest-api-version: 0.1.1, x-runtime: 0.012249, x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
> I/flutter ( 9631): BODY
> I/flutter ( 9631):   {"errors":["Unexpected signature"]}

Do you have any idea what signature error might be about?

**Comment by TatankaConCube** [comment]
hello @aytunch, last message doesn't related to current topic, please close current ticket if you don't have questions about 'correct order of API calls' and create new with detailed description your problem (detailed steps to reproduce, full log which contains request and response).

**Comment by aytunch** [comment]
Hi,
I opened a new issue as yu asked but, I get this probem while I try to get connected with the order you recommended. So I am still not sure if this is resolved or not. Because of this error, I can not send a message:/

**Comment by TatankaConCube** [comment]
we provide [samples](https://github.com/ConnectyCube/connectycube-flutter-samples) for a better understanding ConnectyCube API, please check them out
