### ISSUE TITLE
Unexpected signature

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-sdk-releases#17]
Hi,
I am getting an error while trying to use the sdk. It happens while I try to register a user:

> HEADERS
> I/flutter ( 9631):   {connection: keep-alive, set-cookie: _mkra_ctxt=5ba8a97b44cf66c7d44b4ec4d4e0b65d--422; path=/; max-age=5; HttpOnly; secure, cache-control: no-cache, status: 422 Unprocessable Entity, transfer-encoding: chunked, date: Tue, 24 Nov 2020 21:40:43 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: 8bf35e46-4dc3-4e74-baa8-9f13b681fcbd, connectycube-rest-api-version: 0.1.1, x-runtime: 0.012249, x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
> I/flutter ( 9631): BODY
> I/flutter ( 9631):   {"errors":["Unexpected signature"]}

Do you have any idea what signature error might be about?

**Comment by TatankaConCube** [comment]
please, provide detailed steps to reproduce, and full logs with request and response. Can you reproduce a similar issue on [our samples](https://github.com/ConnectyCube/connectycube-flutter-samples)?

**Comment by aytunch** [comment]
There was a problem with the password
