### ISSUE TITLE
Can send but can not receive messages

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-sdk-releases#18]
I try the 2 scenerios I explain below:
1-register new cube user
2-create user cube session
3-start connection
4-create group dialog
5-listen to message changes
6-send a message
7-receive that message

This works very well however when I try to login an existing user and try to listen to an existing group dialog, i dont receive message changes.
1-login existing user
2-create user cube session
3-start connection
4-get dialogs(confirm user is in a dialog)
5-fetch dialog history(works well)
6-listen to message changes
7-send a message(from cc console I confirm the message is sent successfully)
8-that message is never received from the listener!!

Do you have any idea what might be wrong to cause step 8 to fail?
This is the last part before I have a working group chat module.

**Comment by TatankaConCube** [comment]
There can be two cases, or the user didn't receive the message or listened didn't trigger, for both cases we need a full log from the app stating to getting this error, so, please provide a full log from the flutter console. Additionally, you can see, similar functionality in our [chat_sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample), maybe it will help you to understand your mistake.

**Comment by aytunch** [comment]
I changed my cc repo to a singleton and it worked. it was not a problem about cc
