### ISSUE TITLE
ConferenceClient's method createCallSession not accepting audio calls.

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [ConnectyCube/connectycube-flutter-sdk-releases#25]
`_currentCall = await _callClient.createCallSession(userId, call_type);`

here i passes `CallType.AUDIO_CALL` but still when i am receiving a call its says its a video conference call.

**Comment by TatankaConCube** [comment]
It is an expected case because in the current version of the Conference calls sample we support only CallType.VIDEO_CALL. You can add support for audio calls by yourself.

**Comment by BhavyKoshti9spl** [comment]
what if i want conference audio call ? I am passing audio call and in return callSession should return me its an audio call but it is returning me video call if you can just fix this we can have a feature of conference audio call.

**Comment by TatankaConCube** [comment]
how you check the call type for a session? just call `_currentCall.callType` and it returns 1? please add more details about
> but still when i am receiving a call its says its a video conference call

where you are receiving it? please add detailed steps with description of how you reproduce this issue

BTW, I ran tests in our SDK, and after creating the session with the type `CallType.AUDIO_CALL` this code `session.callType`returns 2 as expected.

**Comment by BhavyKoshti9spl** [comment]
Branch : master in for conference call select_opponents_screen i have started call by _callClient.createCallSession(currentUser.id,CallType.AUDIO_CALL);  

i think while i should receive the receiver call should responde me CallType.AUDIO_CALL but it is returning me 1 that is CallType.VIDEO_CALL and this is happening always.

**Comment by BhavyKoshti9spl** [comment]
after some digging i found that on receiving call in `select_opponents_screen`  `onReceiveNewCal`l did not receives any call types and when we accept the call in `_acceptCall `method is again `createCallSession` without any call types so default in other side video call is created. may be something wrong with the code itself in that branch .

why `createCallSession `2 `times?```

**Comment by TatankaConCube** [comment]
It is that I wrote to you in my first response, now we implemented only video calls in our sample. You can add needed parameters to the signaling message by yourself. Our SDK supports both types of calls.

> why `createCallSession` 2 times?

first time for the caller, second - for the receiver, as usual, what wrong?

**Comment by BhavyKoshti9spl** [comment]
It Worked i just added callType in `_systemMessagesManager` and now conference call is working for both.

Please add this feature to demo so we can have a new feature in demo.

Thanks for the Help!
