### ISSUE TITLE
How to paginate getAllUsers method in flutter SDK ? 

### ISSUE THREAD

**Issue by blackkara** [ConnectyCube/connectycube-flutter-sdk-releases#29]
The `getAllUsers` method returns data including pagination structure(limit, current page, per page etc.) But it takes zero parameter. So how can i pass page related parameters to the this method to list users via pagination on `Flutter` side ? 

Btw, while checking the documents, i saw `https://api.connectycube.com/users` endpoint  that accepts `page`, `per_page` parameters in `Server API` side. 

So, should i make http request to this endpoint instead of Flutter `getAllUsers` ?

**Comment by TatankaConCube** [comment]
In the current version of our SDK, we don't have ready to use functions for getting users by pages. But we have the done query for it. You can try to use the code below for your feature:
```dart
    Map<String, dynamic> params = {
      "page": 1,
      "per_page": 7
    };

    Future<PagedResult<CubeUser>> users = GetUsersQuery.byFilter(null, null, params).perform();
```

**Comment by blackkara** [comment]
Thanks, this is exactly what i'm looking

**Comment by waqarali27324** [comment]
hello
@blackkara  @TatankaConCube did it solves the problem? can you please share paginated users code?

**Comment by TatankaConCube** [comment]
@waqarali27324 why can't you use this example https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/29#issuecomment-753882628? It is a universal method for getting users using filtering, sorting, and any additional parameters you need. All available parameters you can be found here https://developers.connectycube.com/server/users?id=retrieve-all-users
