### ISSUE TITLE
Cant get call after reconnect internet (Flutter)

### ISSUE THREAD

**Issue by caspereus** [ConnectyCube/connectycube-flutter-sdk-releases#3]
in my case when user reconnect internet ,he cannt call and receive call

**Comment by TatankaConCube** [comment]
hello @caspereus, Connectycube Flutter SDK is at alpha development stage and some features not realised yet (automatic session management, automatic chat reconnection, etc.). You can realise it on your app side by adding logic for listening internet connection state and after connection established add logic to relogin to the chat.

**Comment by TatankaConCube** [comment]
today we released a new version, please find out our [documentation](https://developers.connectycube.com/flutter/messaging?id=reconnection) to organize reconnection logic in your app

**Comment by TatankaConCube** [comment]
@caspereus  do you have any updates here?

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
