### ISSUE TITLE
Receive calls in background

### ISSUE THREAD

**Issue by gianlucainnocente** [ConnectyCube/connectycube-flutter-sdk-releases#34]
When will be ready the feature to receive calls with app closed?

Thank you

**Comment by TatankaConCube** [comment]
We have this feature in our roadmap after implementing Push notifications for the Chat sample. At this moment we don't have an end date for the implementation of this feature.

**Comment by gianlucainnocente** [comment]
Thanks

**Comment by gianlucainnocente** [comment]
Hello, any news about that? @TatankaConCube

**Comment by TatankaConCube** [comment]
@gianlucainnocente it is already implemented in the P2P Calls sample using the Push notifications and the Callkit features.
