### ISSUE TITLE
onCallAcceptedByUser not being called

### ISSUE THREAD

**Issue by sowens-csd** [ConnectyCube/connectycube-flutter-sdk-releases#36]
**Platform (use [x])**
[ ] Android
[x ] iOS

**Device info**
Manufacture: Apple
Model: iPad
OS version: 14.4

**Describe the bug:**
The onCallAcceptedByUser callback is not getting called when the remote user accepts the call. I'm trying to get access to the userInfo that is sent in that callback but not having any luck. 

**Steps to Reproduce:**
1. Start with the p2p_call_sample from ConnectyCube
2. Create a new callback listener method in _ConversationCallScreenState with some logging in it
3. Assign the callback listener for the onCallAcceptedByUser to the session in the initState method for ConversationCallScreen
4. Run the sample app, place a call and accept the call on a remote.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**
No logs shown from that method

**Expected behavior:**
Should see a log indicating the callback was called.

**Additional info**
Separate but related problem. I also need to get the userInfo that is sent with the `startCall` method and I don't see how to do that in Flutter. In iOS it is sent to the onReceiveNewSession callback but I don't see it in the Flutter SDK. 

Here's the handler I created:
```dart
  void _onCallAccepted(P2PSession session, int userId,
      [Map<String, String> userInfo]) {
    log("I was called!!!");
  }
```

Here's the changed initState method that assigns the callback:
```dart
  @override
  void initState() {
    super.initState();

    log("initializing ", TAG);
    _callSession.onLocalStreamReceived = _addLocalMediaStream;
    _callSession.onRemoteStreamReceived = _addRemoteMediaStream;
    _callSession.onSessionClosed = _onSessionClosed;
    _callSession.onCallAcceptedByUser = _onCallAccepted;
    log("Callbacks established ", TAG);

    _callSession.setSessionCallbacksListener(this);
    log("Listener set ", TAG);
    if (_isIncoming) {
      _callSession.acceptCall();
    } else {
      _callSession.startCall();
    }
    log("Done initializing ", TAG);
  }
```

**Comment by TatankaConCube** [comment]
@sowens-csd thank you for reporting this issue, we will fix it in the next release. 

About `onReceiveNewSession` callback: in the Flutter SDK we have the [similar](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/call_manager.dart#L70) `onReceiveNewSession` callbak. There you can get the user info via:
```dart
Map<String, String> userInfo = callSession.cubeSdp.userInfo;
```

**Comment by sowens-csd** [comment]
Thanks for the response, that's helpful.

**Comment by sowens-csd** [comment]
The fix looks good to me, I'll close this. Thanks for the help on the other issue, that gave me what I needed to show the caller info.
