### ISSUE TITLE
'Delivered' status doesn't listen any change

### ISSUE THREAD

**Issue by JErazo7** [ConnectyCube/connectycube-flutter-sdk-releases#47]
**Platform (use [x])**
[x] Android
[x] iOS

**Device info**
Emulators: Pixel 4 XL API 30 and Iphone 12 Pro Max  iOS 14.4

**Describe the bug:**
This code doesn't listen any changes.
`MessagesStatusesManager messagesStatusesManager = CubeChatConnection.instance.messagesStatusesManager;
messagesStatusesManager.deliveredStream.listen((messageStatuses){
    print("Message RECEIVED ${messageStatuses.userId}, ${messageStatuses.messageId}, ${messageStatuses.dialogId}");
});`

**Steps to Reproduce:**
1. Download flutter example https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample
2. Comment out the lines 813-815 on chat_dialog_screen.dart  to avoid the 'Read' status listener and to avoid the 'Read' status listener and be able to verify only the behavior of 'Delivered' status
3.  Start a private chat

**Actual result:**
Message status is not updated to delivered

**Additional info**
I am implementing the sdk in another project and it doesn't work either. The skd version is the last stable one in pub.dev

**Comment by TatankaConCube** [comment]
you can fix it by changing line [145](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/chat_sample/lib/src/chat_dialog_screen.dart#L145) 
from
```dart
_cubeDialog.readMessage(message);
```
to
```dart
_cubeDialog.deliverMessage(message);
```

**Comment by JErazo7** [comment]
Thanks so much.  It works perfectly with your solution.
