### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by JErazo7** [ConnectyCube/connectycube-flutter-sdk-releases#49]
Offline support for retrieving dialogs and messages when users don't have internet connection.

**Comment by TatankaConCube** [comment]
This feature not related to Connectycube API. You can realize it on the app side by using any DB plugins for flutter. From the Connectycube side, you have API for getting [dialogs](https://developers.connectycube.com/flutter/messaging?id=list-dialogs) and [messages](https://developers.connectycube.com/flutter/messaging?id=chat-history).

**Comment by JErazo7** [comment]
I think that for developers it adds a lot of value that this is already implemented as part of the skd. Stream Chat has it, I do not see why you do not, it would be a huge plus in the face of the competition.
