### ISSUE TITLE
Push notifications are not sent

### ISSUE THREAD

**Issue by JErazo7** [ConnectyCube/connectycube-flutter-sdk-releases#54]
**Platform (use [x])**
[x] Android
[x] iOS

**Device info**
Apple inc
Model:  iPhone X 
iOS 14.4.2

Xiaomi 
Model:  Note 9s
Android 10 

When you sent a message from the iOS device to Android or vice versa, the push notification arrives but 25% of the time.

If I send a push notification from the ConnectyCube console, the notification reaches both devices immediately, so it is not an FCM or configuration problem.

**Expected behavior:**
When sending a message, the receiving device is notified immediately

**Additional info**
In the android emulator it does not work even with google services installed and sending from the ConnectyCube console

**Comment by TatankaConCube** [comment]
@JErazo7 here one note, the server will send chat push notification only in case when user-receiver of the message not logged in to the chat. Check this case first. Then you can check, did the server sent the notification or not in the Connectycube admin panel by path Home -> Your app -> Push notifications -> Queue.

**Comment by JErazo7** [comment]
Is there any way to receive notifications when user is logged in to the chat? The user experience will be affected if they are not notified while they are logged.

**Comment by TatankaConCube** [comment]
It is common practice, when a user in the app, he sees notifications from the app (badges, popups, etc.) if the user leaves the application he sees push notifications. But for your case you will receive messages in the messages listener, you can show local notification from it if the app placed in the background.

Please add more details about your needs and we will try to suggest an optimal solution for your cases.
