### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by dinesh-gajjar** [ConnectyCube/connectycube-flutter-sdk-releases#55]
Hi, Any plan to support desktop versions (macOS, windows and linux) in coming release?

**Comment by TatankaConCube** [comment]
We are investigating this feature, but at this moment we don't have an end date for the implementation of this feature.

**Comment by TatankaConCube** [comment]
The required feature was added in today's [release](https://pub.dev/packages/connectycube_sdk/versions/2.0.3), check it)))
