### ISSUE TITLE
About storage limit

### ISSUE THREAD

**Issue by brizaldi** [ConnectyCube/connectycube-flutter-sdk-releases#56]
Hi, I'm just wondering is there a limit for connectycube storage? because It seems I can't find any info about it on the [pricing page](https://connectycube.com/pricing/) or the documentation.

**Comment by TatankaConCube** [comment]
The Connectycube server doesn't have limits for the storage except for the size of an uploaded file, it shouldn't be more than 100MB.

**Comment by brizaldi** [comment]
that's very generous from you guys, even on free tier there's no limit?

**Comment by TatankaConCube** [comment]
yes, it is actual for the Free plan too. Usually, our customers use storage for chat attachments and it doesn't require a lot of space on the storage.
