### ISSUE TITLE
CreateSession Error (Error: max must be in range 0 < max ≤ 2^32, was 0)

### ISSUE THREAD

**Issue by gjmg2303** [ConnectyCube/connectycube-flutter-sdk-releases#58]
**Platform (use [x])**
[x ] Android
[x ] iOS

try with flutter web

**Device info**
Manufacture: [e.g. Apple inc.]
Model: [e.g. iPhone 11 Pro Max]
OS version: [e.g. 13.5.2]

**Describe the bug:**

Hello, i am Juan. And i am very happy with connectycube with flutter. 
On android and ios p2p video calling works WONDERFULLY!!!! But when execute in flutter web chrome . 
I know you guys are working on it. but since I have the connection at the beginning of my program and I am testing my app in chrome. I thought that the program would not crash from CreateSession, that's why I tried.
Maybe the error helps to guide you to the web flutter tool

Another question: Where i can see the log?

Thanks and happy day

createSession(user).then((cubeSession){
      print("Session was created");
    }).catchError((error){

      print("Error was occured during create sessin " + error.toString());
    });

error.toString() = (Error: max must be in range 0 < max ≤ 2^32, was 0)

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**

createSession(user).then((cubeSession){
      print("Session was created");
    }).catchError((error){

      print("Error was occured during create sessin " + error.toString());
    });

error.toString() = (Error: max must be in range 0 < max ≤ 2^32, was 0)

or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
Thank you for reporting this issue, yes, we know about this issue if try to use our SDK in a web app. Unfortunately, we not ready to provide SDK for Flutter web, and there we have a lot of problems related to our dependency libs which don't support web too.

**Comment by gjmg2303** [comment]
Thank you very much for your reply.
Yes, the problem was clear, it would have to be something with the web, because in Ios and android it works fantastic.
IF I can help you with something to speed up work and be able to release the version. I am at your service.
Good morning, and thanks again

**Comment by TatankaConCube** [comment]
will be fixed after implementation of https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/45
