### ISSUE TITLE
Ringtone sound is not working

### ISSUE THREAD

**Issue by shatanikmahanty** [ConnectyCube/connectycube-flutter-sdk-releases#59]
**Platform (use [x])**
- [x] Android
- [ ] iOS

**Describe the bug:**

Notification sound is not working for p2p calls

**Additional info**

I am getting incoming call notifications but the ringtone is not working

I think adding this code into the notification_manager.kt file in createCallNotification function will fix the problem but I am open to suggestion to fix the problem in case it is something wrong that I am writing in code.

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                mChannel = new NotificationChannel(CHANNEL_ID, Utils.CHANNEL_NAME, NotificationManager.IMPORTANCE_HIGH);
                mChannel.setLightColor(Color.GRAY);
                mChannel.enableLights(true);
                mChannel.setDescription(Utils.CHANNEL_SIREN_DESCRIPTION);
                AudioAttributes audioAttributes = new AudioAttributes.Builder()
                        .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                        .setUsage(AudioAttributes.USAGE_NOTIFICATION)
                        .build();
                mChannel.setSound(soundUri, audioAttributes);

                if (mNotificationManager != null) {
                    mNotificationManager.createNotificationChannel( mChannel );
                }
        }
```

**Comment by TatankaConCube** [comment]
the issue is not related to this repo, please create the ticket for [suitable](https://github.com/ConnectyCube/connectycube-flutter-call-kit) repo
