### ISSUE TITLE
last_message_date_sent is reporting wrong data

### ISSUE THREAD

**Issue by amitkhairnar44** [ConnectyCube/connectycube-flutter-sdk-releases#6]
I sent a message with dateSent as 1597739171353 (this value was fetched from `DateTime.now().millisecondsSinceEpoch`).
Then after a while i checked the dialog and found out that `last_message_date_sent` is wrong and `last_message` is correct.

`last_message_date_sent` is wrong every time i fetch the dialog list.

Expected: `1597739171353`
Got: `1597739181`. This value is short which causes the date to be `Jan 19 1970 17:18:59` instead of `Aug 18 2020 13:56:11`.

**Comment by TatankaConCube** [comment]
hello @amitkhairnar44, this is the server-side feature, it saves `last_message_date_sent` in seconds, it is expected behavior for ConnectyCube server.

**Comment by amitkhairnar44** [comment]
@TatankaConCube Ohh I didn't knew that. Thank you for updating.
