### ISSUE TITLE
relogin() should return future 

### ISSUE THREAD

**Issue by developerpaaji** [ConnectyCube/connectycube-flutter-sdk-releases#60]
Hey when chat connection is closed then we have to relogin() and after then only we can send request but in order for latter to happen we will need to wait for former right? For this Future need to be return from relogin() because

- if connection state is closed then we are doing login() which returns future.
- if we are reconnecting which in return openSocket() which also returns future.

**Comment by TatankaConCube** [comment]
The method `reconnect()` from `xmpp_stone` lib doesn't return `Future` and we can not change it without changes in this lib. 
For your case, you can orient on `CubeChatConnectionState`, after success relogin at the end it will be changed to `Ready`.
