### ISSUE TITLE
Sdk crashing in middle of app working

### ISSUE THREAD

**Issue by developerpaaji** [ConnectyCube/connectycube-flutter-sdk-releases#63]
: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: ErrorPacket: {type: cancel, code: 503, condition: Condition.service_unavailable, text: Service not available.}

**Comment by TatankaConCube** [comment]
Please, provide the full log, not only the error message.

**Comment by developerpaaji** [comment]
I/flutter (22999): SocketException: OS Error: Connection timed out, errno = 110, address = storage.googleapis.com, port = 42364
I/flutter (22999): Chat Connection CubeChatConnectionState.ForceClosed
E/flutter (22999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = chat.connectycube.com, port = 45702
E/flutter (22999): 
I/flutter (22999): Chat Connection CubeChatConnectionState.Reconnecting

**Comment by TatankaConCube** [comment]
It looks like a problem with the internet connection because in your log you have the similar error with `storage.googleapis.com`. 
Please, attach the full log as I asked before, not only error messages.

**Comment by developerpaaji** [comment]
This error is coming suddenly in middle of app and not because of internet. I tried turning off and on my internet in phone but this error didnot came. As i said this error comes at very unexpected time.

**Comment by TatankaConCube** [comment]
the requested info wasn't provided for a long time, closing
