### ISSUE TITLE
User signup fails if we pass value to "tags" parameter of CubeUser

### ISSUE THREAD

**Issue by amitkhairnar44** [ConnectyCube/connectycube-flutter-sdk-releases#7]
Hi, I'm getting an error while signing up user. This will only occur if we pass value to the `tags` parameter of the `CubeUser`.

```dart
Set<String> tags = Set();
tags.add("user");
CubeUser user = CubeUser(
    tags: tags,
    email: "dummyemail@gmail.com",
    fullName: "Dummy guy",
    password: "password",
    login: "dummyguy");
```

`Converting object to an encodable object failed: Instance of '_CompactLinkedHashSet<String>'`

**Comment by amitkhairnar44** [comment]
Looks like Set is not Encodable right now.

Error reproduced in DartPad : https://dartpad.dev/c8a014b237d2bcbf8c08af1e5e9bf254

**Comment by TatankaConCube** [comment]
yes, you are right, we will fix it in next release

**Comment by amitkhairnar44** [comment]
Thank you @TatankaConCube

**Comment by amitkhairnar44** [comment]
Instead of Set we can use List.

**Comment by TatankaConCube** [comment]
today we released a [new version](https://pub.dev/packages/connectycube_sdk/changelog) with fixes for this problem, please use it

**Comment by amitkhairnar44** [comment]
Thank you, I'll check it 👍
