### ISSUE TITLE
Support In Privacy List @ Flutter SDK

### ISSUE THREAD

**Issue by aviyam181199** [ConnectyCube/connectycube-flutter-sdk-releases#71]
**Is your feature request related to a problem? Please describe.**
As part of Apple's policy, apps need to provide the option to block other client (Guideline 1.2 - Safety - User Generated Content). This guideline require each developer made a blocking mechanism by himself.

**Describe the solution you'd like**
The Solution I suggest is exactly like in your JS SDK, [Privacy Black List](https://developers.connectycube.com/js/messaging?id=privacy-black-list). P.S: If you'll make the SDK public (#1) the community can add this feature, maybe developers that know JS and Flutter can make it easily because it's already implemented by you

**Describe alternatives you've considered**
Currently I'm trying to move this logic to the server side that is in JS.

**Comment by TatankaConCube** [comment]
we added the Privacy List feature to our Flutter road map, but we don't have an end date for its implementstion.

**Comment by TatankaConCube** [comment]
the required feature was published today in [2.0.8](https://pub.dev/packages/connectycube_sdk/versions/2.0.8). It works in the same way as in the JS DSK, more [there](https://developers.connectycube.com/flutter/messaging?id=privacy-black-list).
