### ISSUE TITLE
CIdP for Flutter

### ISSUE THREAD

**Issue by imariman** [ConnectyCube/connectycube-flutter-sdk-releases#72]
**Is your feature request related to a problem? Please describe.**
I want to use CIdP since I have an external database. But there is no special method for CIdP, and I can't authenticate my users.

**Describe the solution you'd like**
A special method to authenticate users via CIdP would be awesome. Or if CIdP authentication is currently possible, I kindly ask you to share an example code.

**Comment by TatankaConCube** [comment]
@imariman  you do not need the separated methods for it. Use common methods for signing via login and password or create a session with a user. Then in the Connectycube admin panel, you can use these parameters as parameters for requests on your server. We provided a detailed example in the Connectycube admin panel, how to map the Connectycube parameters to parameters of request on your server. For example:
```json
{"param_1": "#{login}", "param_2": "#{password}"}
```
here `#{login}` is a login that you set on a sign-in request from the SDK. Other parameters work in the same way.

**Comment by imariman** [comment]
@TatankaConCube  I can create a session, but somehow I can't login to ConnectyCubeChat. 

CODE:
var cubeUser = CubeUser(
        id: int.parse(u.id),
        email: u.email,
        login: u.username,
        password: "Bearer $tok",
      );
await createSession(cubeUser);
CubeChatConnectionSettings.instance.totalReconnections = 0;
var user = await CubeChatConnection.instance.login(cubeUser);

LOGS:
flutter: CB-SDK: : *********************************************************
flutter: *** RESPONSE *** 201 *** 594bca89-d843-4b10-956a-526905ca9d03 ***
flutter: HEADERS
flutter:   {cb-token-expirationdate: 2021-12-30 15:28:20 UTC, connection: keep-alive, date: Thu, 30 Dec 2021 13:28:20 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 595, access-control-expose-headers: CB-Token-ExpirationDate, content-type: application/json; charset=utf-8, server: nginx/1.16.1}
flutter: BODY
flutter:   {"session":{"created_at":"2021-12-30T13:28:20.875Z","updated_at":"2021-12-30T13:28:20.875Z","application_id":4312,"token":"51C179DABC9C91F3E9B71B91BA23FB1BC7B8","nonce":605075566,"ts":1640870899,"user_id":5284619,"user":{"_id":"61cdac6a7442a90062a43919","id":5284619,"created_at":"2021-12-30T12:56:10Z","updated_at":"2021-12-30T13:28:20Z","login":"meteh","full_name":"Metehan Arıman","external_id":"293","last_request_at":null,"email":null,"phone":null,"website":null,"twitter_id":null,"external_user_id":null,"facebook_id":null,"custom_data":null,"user_tags":null,"avatar":null},"id":5284619}}
flutter:
flutter: CB-SDK: CubeChatConnection: [login] userId: 293, null
flutter: CB-SDK: CubeChatConnection: Chat connection SocketOpening
flutter: CB-SDK: CubeChatConnection: Chat connection SocketOpened
flutter: CB-SDK: CubeChatConnection: Chat connection AuthenticationFailure
flutter: ChatConnectionException: Open connection error: AuthenticationFailure 
flutter: CB-SDK: CubeChatConnection: Chat connection Closing
flutter: CB-SDK: CubeChatConnection: Chat connection Closed

CUSTOM IDENTITY PROVIDER SETTINGS: 
Request Headers: {"Authorization": "#{password}"}
Response Params:  {"uid": "#{user.uid}", "login": "#{user.login}", "full_name": "#{user.fill_name}"}

**Comment by imariman** [comment]
Alright, I made a small change and authenticated.

CODE:
var sess = await createSession(cubeUser);
CubeUser user = CubeUser(id: sess.userId, password: sess.token);
await CubeChatConnection.instance.login(user);


Thanks for your time and help. 👍
