### ISSUE TITLE
Not Received Push notification in chat

### ISSUE THREAD

**Issue by khyati08** [ConnectyCube/connectycube-flutter-sdk-releases#73]
**Platform (use [x])**
[] Android
Nexus 4
Samsung M42
Xiaomi note 4

**Device info**
Manufacture: [e.g. Apple inc.]
Model: [e.g. iPhone 11 Pro Max]
OS version: [e.g. 13.5.2]

**Describe the bug:**
In Chat, I am sending chat messages but not receiving push notifications on the device.

**Logs:**
```
[log] ---Xmpp Receiving:---
[log] <message to="5286907-5588@chat.connectycube.com" xmlns="jabber:client" type="chat" id="61d434d178e618b6d39d98ef" from="5286908-5588@chat.connectycube.com/flutter_d6151ace2887ebf4"><body>fffff</body><extraParams xmlns="jabber:client"><date_sent>1641297105</date_sent><save_to_history>1</save_to_history><dialog_id>61ced4c0df714200200747e5</dialog_id><message_id>61d434d178e618b6d39d98ef</message_id></extraParams><markable xmlns="urn:xmpp:chat-markers:0"/></message>
I/flutter ( 6348): CB-SDK: : Receive PRIVATE chat message 61d434d178e618b6d39d98ef

**Comment by TatankaConCube** [comment]
for receiving the push notifications your device should be offline, which means that you should do [logout](https://developers.connectycube.com/flutter/messaging?id=disconnect) from the chat or mark the chat connection as [inactive](https://developers.connectycube.com/flutter/messaging?id=mark-a-client-as-activeinactive).

**Comment by khyati08** [comment]
Working now Thank you :)
