### ISSUE TITLE
not able to accept call in ios

### ISSUE THREAD

**Issue by geetakher** [ConnectyCube/connectycube-flutter-sdk-releases#78]
I am using your latest sample code for the flutter for the p2p call sessions not getting any proper log for the issue.

Where i am getting issue in below listed points:
1.Android phone to android phone call is not able to accept/reject on termination mode
2.getting two buttons for accept/reject in ios and some times different two buttons for accept reject
3.background mode, ios call not accepting / reject
https://drive.google.com/drive/folders/1w7NI2qcvFuxwy2DFTi7V-IJH1KMm-eRX?usp=sharing
here is screen recording for the issue when ever i am getting buttons like and not ringing phone as well

**Comment by TatankaConCube** [comment]
if your issue still is actual please create a new ticket with the required details
