### ISSUE TITLE
Upgrade flutter_webrtc to 0.8.2

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-sdk-releases#79]
Right now this plugin relies on flutter_webrtc 0.8.1
And when the newly released Flutter 2.10.0 is used, we can not compile our apps.
Please make sure Connecty cube apps run fine in Flutter 2.10.0 with the latest packages and dependencies.

> ^
> In module 'WebRTC' imported from [/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.1/ios/Classes/FlutterRTCMediaStream.m:3]():
>     In module 'AVFoundation' imported from [/build/ios/Debug-development-iphonesimulator/XCFrameworkIntermediates/WebRTC-SDK/WebRTC.framework/Headers/RTCVideoFrame.h:11]():
>     [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1](): note: 'devicesWithMediaType:' has been explicitly marked deprecated here
>     + (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaType API_DEPRECATED("Use AVCaptureDeviceDiscoverySession instead.", ios(4.0, 10.0), macos(10.7, 10.15)) API_UNAVAILABLE(tvos);
>     ^
>     5 warnings generated.
> In file included from [flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.1/ios/Classes/FlutterRTCFrameCapturer.m:10]():
>     In file included from [/ios/Pods/Libyuv/headers/libyuv.h:16]():
>     In file included from [/ios/Pods/Headers/Public/libyuv/convert.h:21]():
>     [Pods/Headers/Public/libyuv/planar_functions.h:563:26](): warning: this function declaration is not a prototype [-Wstrict-prototypes]
>     ARGBBlendRow GetARGBBlend();
>                              ^
>                               void
>     1 warning generated.
> [/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.6/ios/Classes/FLTFirebaseFunctionsPlugin.m:85:16](): warning: 'useFunctionsEmulatorOrigin:' is deprecated: Use useEmulator(host:port:) instead. [-Wdeprecated-declarations]
>         [functions useFunctionsEmulatorOrigin:origin];
>                    ^
>     In module 'FirebaseFunctions' imported from [/Pods/Headers/Public/Firebase/Firebase.h:54]():
>     [/Pods/FirebaseFunctions/FirebaseFunctions/Sources/Public/FirebaseFunctions/FIRFunctions.h:92:24](): note: 'useFunctionsEmulatorOrigin:' has been explicitly marked deprecated here
>             __attribute__((deprecated("Use useEmulator(host:port:) instead.")));
>                            ^
>     1 warning generated.
> [/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.6/ios/Classes/FLTFirebaseFunctionsPlugin.m:85:16](): warning: 'useFunctionsEmulatorOrigin:' is deprecated: Use useEmulator(host:port:) instead. [-Wdeprecated-declarations]
>         [functions useFunctionsEmulatorOrigin:origin];
>                    ^
>     In module 'FirebaseFunctions' imported from [Pods/Headers/Public/Firebase/Firebase.h:54]():
>     [/Pods/FirebaseFunctions/FirebaseFunctions/Sources/Public/FirebaseFunctions/FIRFunctions.h:92:24](): note: 'useFunctionsEmulatorOrigin:' has been explicitly marked deprecated here
>             __attribute__((deprecated("Use useEmulator(host:port:) instead.")));
>                            ^
>     1 warning generated.
> : Error: The non-abstract class 'RTCPeerConnectionNative' is missing implementations for these members:
> ../…/native/rtc_peerconnection_impl.dart:19
>      - RTCPeerConnection.restartIce
>     Try to either
>      - provide an implementation,
>      - inherit an implementation from a superclass or mixin,
>      - mark the class as abstract, or
>      - provide a 'noSuchMethod' implementation.

**Comment by TatankaConCube** [comment]
the new version was released today, we will update our std soon

**Comment by aytunch** [comment]
@TatankaConCube Is there an ETA for this dependency upgrade?

**Comment by TatankaConCube** [comment]
I plan to release it today or tomorrow

**Comment by TatankaConCube** [comment]
@aytunch  the version 2.0.11 with updated `flutter_webrtc` lib was published

**Comment by aytunch** [comment]
@TatankaConCube thank you. I am trying now with Flutter 2.10.0
