### ISSUE TITLE
Android RTCRtpSenderNative.replaceTrack has type MediaStreamTrack .....WebRTC Error

### ISSUE THREAD

**Issue by Codzaa** [ConnectyCube/connectycube-flutter-sdk-releases#80]
**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[x] Windows
[] Web

**Device info**
OS version: [Windows 11]
Flutter 2.10.5
ConnectyCubeSDK ^2.1.0

**Describe the bug:**
I made a new Flutter App, I added ConnectyCube SDK, I  tried running the App on my Android Emulator and my actual Android Device but I get the following errors.

![image](https://user-images.githubusercontent.com/35093657/167812366-892c8156-af7f-469e-a7b8-932e9bb94f8b.png)

**Steps to Reproduce:**
1.  New Flutter App
2.  Add ConnectyCube SDK
3. Import the library anywhere in you project (import 'package:connectycube_sdk/connectycube_sdk.dart';)
4. Run or Build for Android 

**Actual result:**

![image](https://user-images.githubusercontent.com/35093657/167812366-892c8156-af7f-469e-a7b8-932e9bb94f8b.png)

**Expected behavior:**
 Should Build/Run with no Error

**Additional info**
 Thanks

**Comment by TatankaConCube** [comment]
it looks like the issue is related to the latest updates of the `flutter_webrtc` lib, we will check it and release the update later, before it you can try to override the dependency of the lib `webrtc_interface` to the previous version (1.0.3) by adding the next lines to your `pubspec.yaml` file:

```yam
dependency_overrides:
  webrtc_interface: 1.0.3
```

**Comment by TatankaConCube** [comment]
@Codzaa today we have published the new version (2.1.1) with the required fix, try it
