### ISSUE TITLE
RTCVideoRenderer

### ISSUE THREAD

**Issue by wrteam02** [ConnectyCube/connectycube-flutter-sdk-releases#83]
**Platform (use [x])**
Flutter

not able to run app, getting error
-----
connectycube_sdk: 2.2.2
----

flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.9.5/lib/src/native/rtc_video_renderer_impl.dart:11:7: Error: The non-abstract class 'RTCVideoRenderer' is missing implementations for these members:
 - VideoRenderer.onFirstFrameRendered
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RTCVideoRenderer extends ValueNotifier<RTCVideoValue>
      ^^^^^^^^^^^^^^^^
/System/Volumes/Data/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/webrtc_interface-1.0.8/lib/src/rtc_video_renderer.dart:51:13: Context: 'VideoRenderer.onFirstFrameRendered' is defined here.
  Function? onFirstFrameRendered;
            ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/System/Volumes/Data/fluttersdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/System/Volumes/Data/fluttersdk/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

-----
Flutter doctor
-----
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /System/Volumes/Data/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tech/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM E225F (mobile) • 192.168.1.112:39915 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos               • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)      • chrome              • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by TatankaConCube** [comment]
looks like the issue is the same with [it](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/82), try the [solution](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/82#issuecomment-1239149703) from that thread
