### ISSUE TITLE
Add some Comments in Code

### ISSUE THREAD

**Issue by sikandernoori** [ConnectyCube/connectycube-flutter-sdk-releases#84]
It would be nice if developer knows what the code is doing, some code comments helps in this regard.

Appreciate if you can add this in code.

**Comment by TatankaConCube** [comment]
All public APIs are covered with the documentation and described in more detail on our website https://developers.connectycube.com/flutter/
We have separated ticket for adding the Dart documentation to the code but it requires a lot of time and for now, we cover with the Dart documentation only new API and features.
