### ISSUE TITLE
platform_device_id is not compatible with latest gradle / Kotlin versions

### ISSUE THREAD

**Issue by Lecroyce** [ConnectyCube/connectycube-flutter-sdk-releases#88]
[x] Android / Flutter

"The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':platform_device_id' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"

Your Flutter package uses platform_device_id which uses an old Kotlin version.
I have upgraded the gradle for Android but the platform_device_id is too old and not maintained.

**Steps to Reproduce:**
1. Apply connectycube_sdk 2.4.1 to your Flutter project
2. Use a Flutter project with a newer Kotlin version (here 1.6.20)
3. Debug the app and receive the error

**Additional info**
In your Flutter Samples you already used device_info_plus, which provides the exact same features.

**Comment by TatankaConCube** [comment]
@Lecroyce the version [2.4.2](https://pub.dev/packages/connectycube_sdk/versions/2.4.2) was published, please try it.

**Comment by Lecroyce** [comment]
Works perfectly!
