### ISSUE TITLE
Problem when entering AudioCall

### ISSUE THREAD

**Issue by pedrostick3** [ConnectyCube/connectycube-flutter-sdk-releases#89]
**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Google
Model: Pixel 4
OS version: Android API 30

**Describe the bug:**
When i enter in an audiocall ( CallType.AUDIO_CALL ) it apears a problem in line 18 that has `MediaStreamTrack videoTrack = mediaStream.getVideoTracks().first;` on file `connectycube_sdk-2.5.0\lib\src\calls\conference\conference_peer_connection.dart`.

**Steps to Reproduce:**
1. Create a call session `ConferenceClient.instance.createCallSession(userId, callType: CallType.AUDIO_CALL)`.
2. Enter in AudioCall using method `callSession.joinDialog()`.
3. Error appears refering a "Bad state: No element" in your library on `connectycube_sdk-2.5.0\lib\src\calls\conference\conference_peer_connection.dart` in method `setMediaStream`;

**Logs:**
```
/flutter (24973): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (24973): #0      List.first (dart:core-patch/growable_array.dart:343:5)
E/flutter (24973): #1      ConferencePeerConnection.setMediaStream
conference_peer_connection.dart:18
E/flutter (24973): #2      PeerConnection._createPeerConnection
peer_connection.dart:110
E/flutter (24973): <asynchronous suspension>
```

**Actual result:**
Everytime i enter in audio call this bug comes up.

**Expected behavior:**
Enter in audio call without problems.

**Additional info**
I fixed it by going to this file `connectycube_sdk-2.5.0\lib\src\calls\conference\conference_peer_connection.dart` in method `setMediaStream` and change:
- Line `MediaStreamTrack videoTrack = mediaStream.getVideoTracks().first;` to `MediaStreamTrack? videoTrack = mediaStream.getVideoTracks().isNotEmpty ? mediaStream.getVideoTracks().first : null;`;
- and in same method change this:
```
pc.addTransceiver(
  track: videoTrack,
  kind: RTCRtpMediaType.RTCRtpMediaTypeVideo,
  init: initVideo,
);
```
to this:
```
if (videoTrack != null) {
  pc.addTransceiver(
    track: videoTrack,
    kind: RTCRtpMediaType.RTCRtpMediaTypeVideo,
    init: initVideo,
  );
}
```

Hope it helped :)
Please fix this bug and contact me when you merge this into a new package version so i can update it ;)

**Comment by TatankaConCube** [comment]
thank you for your investigation and the solution, will check it and fix it soon

**Comment by pedrostick3** [comment]
This issue is resolved, thanks :)
