### ISSUE TITLE
ava.lang.UnsatisfiedLinkError: Sample App cannot compile

### ISSUE THREAD

**Issue by rdhillbb** [ConnectyCube/connectycube-flutter-sdk-releases#9]
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[ ] iOS

**Device info**
Manufacture: Realme 6 Plus
Model: RMX2061
OS version: Android 10

Compilation error.

**Steps to Reproduce:**
1. Debugg Run VS Code

Log

 Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(10691): FATAL EXCEPTION: main
E/AndroidRuntime(10691): Process: com.connectycube.flutter.p2p_call_sample, PID: 10691
E/AndroidRuntime(10691): java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
E/AndroidRuntime(10691): 	at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
E/AndroidRuntime(10691): 	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:293)
E/AndroidRuntime(10691): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.<init>(FlutterWebRTCPlugin.java:106)
E/AndroidRuntime(10691): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.registerWith(FlutterWebRTCPlugin.java:91)
E/AndroidRuntime(10691): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)

**Comment by rdhillbb** [comment]
I ran the following commands and fixed the issue
flutter clean
 flutter doctor
flutter upgrade

Not sure why this resolved my issue when it was working before. I guess I fat fingered some place.

**Comment by gianlucainnocente** [comment]
Same problem here. Is this normal? This happens only building release version.
