### ISSUE TITLE
IOS Voip push notification not working as expected

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [ConnectyCube/connectycube-flutter-sdk-releases#95]
**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Android Emulator
Model: Pixel 3a XL
OS version: API 33

**Describe the bug:**
Voip push notifications event created successfully, the notification appears in the Push notifications queue as sent but the opponent does not receive the push notification. The issue seems to be due to connectycube sending the notification on the wrong subscription environment (production) even after setting the params.environment to (development) [manually setting the notification event to development does not work]

**Steps to Reproduce:**
1. Authenticate, login and connect user to chat
2. Create a push notification payload (before calling the session.startCall() method)
3. Start P2P session call using the session.startCall() method
4. Install Ios application with schema set to "release build"  ***** might be important *****

**Logs:**
```
1. Push notification event creation logs:

I/flutter (13490): *** RESPONSE *** 201 *** d47ba506-e046-4a39-90c3-bc42ec9c40ba ***
I/flutter (13490): HEADERS
I/flutter (13490):   {cb-token-expirationdate: 2023-05-30 07:41:21 UTC, connection: keep-alive, date: Tue, 30 May 2023 05:41:21 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 1402, access-control-expose-headers: CB-Token-ExpirationDate, Date, content-type: application/json; charset=utf-8, server: nginx/1.23.1}
I/flutter (13490): BODY
I/flutter (13490):   [{"event":{"_id":"64758c819b604c002fdb82da","event_type":"one_shot","message":"eyJtZXNzYWdlIjoiSW5jb21pbmcgQXVkaW8gY2FsbCIsImNhbGxfdHlwZSI6Miwic2Vzc2lvbl9pZCI6IjkwNjY4ZmMzLWI3NDYtNDgzNS05ODIwLWQ3MzRkNWYwNzIwNSIsImNhbGxlcl9pZCI6NzgxMjQxOCwiY2FsbGVyX25hbWUiOiJDdWJlIFVzZXIiLCJjYWxsX29wcG9uZW50cyI6Ijc5MTIzNDQiLCJzaWduYWxfdHlwZSI6InN0YXJ0Q2FsbCIsImlvc192b2lwIjp0cnVlLCJoYXNfdmlkZW8iOmZhbHNlLCJjYWxsZXJfaWRfdHlwZSI6Im51bWJlciJ9","user_id":7812418,"environment":"development","date":null,"period":null,"kind":"API","end_date":null,"active":true,"created_at":"2023-05-30T05:41:21Z","updated_at":"2023-05-30T05:41:21Z","tag_query":null,"name":null,"notification_channel":{"name":"apns_voip"},"id":606450032}},{"event":{"_id":"64758c819b604c002fdb82db","event_type":"one_shot","message":"eyJtZXNzYWdlIjoiSW5jb21pbmcgQXVkaW8gY2FsbCIsImNhbGxfdHlwZSI6Miwic2Vzc2lvbl9pZCI6IjkwNjY4ZmMzLWI3NDYtNDgzNS05ODIwLWQ3MzRkNWYwNzIwNSIsImNhbGxlcl9pZCI6NzgxMjQxOCwiY2FsbGVyX25hbWUiOiJDdWJlIFVzZXIiLCJjYWxsX29wcG9uZW50cyI6Ijc5MTIzNDQiLCJzaWduYWxfd

2. Push notifcation event log from admin dashboard:

{"_id":"64757e5a45c1d6002f6a960d","event_id":"64757e5a1833b1002f429c32","delivered":0,"failed":0,"failed_device_tokens":[],"failed_device_tokens_reason":[],"processed_at":"2023-05-30T04:40:58Z","general_errors":["Error: {\"app_id\":7108,\"event_id\":\"64757e5a1833b1002f429c32\"} | Can't find any subscriptions {\"environment\":\"production\",\"notification_channel_id\":6,\"user_id\":{\"$in\":[7912344]}}"]}

3. Opponent apns voip subscription data:

SUBSCRIPTION ID: 6745150
NOTIFICATION CHANNEL: apns_voip
PUSH TOKEN: <token removed>
BUNDLE IDENTIFIER: <bundle removed>
ENVIRONMENT: development
UPDATED AT: 2023-05-30T04:39:33.995Z
DEVICE UDID: <device id removed>
PLATFORM: ios

```

**Actual result:**
No Voip push notification received on the opponent device

**Expected behavior:**
Receive Voip push notification on opponent device

**Additional info**
All settings required for the receiving voip push notification are in place and have been tested as working by sending voip notifications through other tools

****** Code used for creating subscription:

CreateSubscriptionParameters parameters = CreateSubscriptionParameters();
    parameters.pushToken = token;

    parameters.environment =
        kReleaseMode ? CubeEnvironment.PRODUCTION : CubeEnvironment.DEVELOPMENT;

    if (Platform.isAndroid) {
      parameters.channel = NotificationsChannels.GCM;
      parameters.platform = CubePlatform.ANDROID;
    } else if (Platform.isIOS) {
      parameters.channel = NotificationsChannels.APNS_VOIP;
      parameters.platform = CubePlatform.IOS;
    }

    var deviceInfoPlugin = DeviceInfoPlugin();

    var deviceId;

    if (kIsWeb) {
      var webBrowserInfo = await deviceInfoPlugin.webBrowserInfo;
      deviceId = base64Encode(utf8.encode(webBrowserInfo.userAgent ?? ''));
    } else if (Platform.isAndroid) {
      var androidInfo = await deviceInfoPlugin.androidInfo;
      deviceId = androidInfo.id;
    } else if (Platform.isIOS) {
      var iosInfo = await deviceInfoPlugin.iosInfo;
      deviceId = iosInfo.identifierForVendor;
    } else if (Platform.isMacOS) {
      var macOsInfo = await deviceInfoPlugin.macOsInfo;
      deviceId = macOsInfo.computerName;
    }

    parameters.udid = deviceId;

    var packageInfo = "<com.example.app>";
    parameters.bundleIdentifier = packageInfo;

    createSubscription(parameters.getRequestParameters())
        .then((cubeSubscriptions) {
      logger.d('[subscribe] subscription SUCCESS');
      repository.storeSubscriptionToken(token);
      for (var subscription in cubeSubscriptions) {
        if (subscription.device!.clientIdentificationSequence == token) {
          repository.storeSubscriptionID(subscription.id!);
        }
      }
    }).catchError((error) {
      logger.e(
        '[subscribe] subscription ERROR: $error',
      );
    });
    
****** Code used for sending notification:
try {
      CreateEventParams params = CreateEventParams();

      params.parameters = {
        'message':
            "Incoming ${currentCallSession!.callType == CallType.VIDEO_CALL ? "Video" : "Audio"} call",
        'call_type': currentCallSession!.callType,
        'session_id': currentCallSession!.sessionId,
        'caller_id': currentCallSession!.callerId,
        'caller_name': 'Cube User',
        'call_opponents': currentCallSession!.opponentsIds.join(','),
        'signal_type': 'startCall',
        'ios_voip': 1,
        "has_video": false,
        "caller_id_type": "number",
      };

      params.notificationType = NotificationType.PUSH;
      params.environment = CubeEnvironment.DEVELOPMENT;
      params.usersIds = super.currentCallSession!.opponentsIds.toList();

      logger.w("push notification environment is: ${params.environment}");
      final CubeEvent cubeEvent = params.getEventForRequest();

      logger.e(cubeEvent.environment);
      final events = await createEvent(cubeEvent);

      if (events.isNotEmpty) {
        logger.d(
            "events list is not empty hence the push notification event created");
        return true;
      }
      logger.e(
          "events list is empty hence the push notification event was not created");
      return false;
    } catch (e) {
      logger.e("An error occurred while creating push notification");
      logger.e(e);
      return false;
    }
  }

**Comment by AbdurrehmanSubhani** [comment]
Hey, thanks for the quick reply, after reading your response, i rechecked the apns push certificate and it turned out the bundle identifier had xxx.xxx.xxx.(voip) appended at the end. Uploaded the correct certificate and now im able to receive the notification and display the incoming call. Again thanks for the quick help!!
👍

**Comment by venbrinoDev** [comment]
Hi @TatankaConCube we are APNS Authentication Token (JWT) and we notice that when we run app on release mode the token get removed from the user , but runs fine on development 

any help here
