### ISSUE TITLE
Is there any expected date for "Monitor session connections state" feature, any time soon?

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [ConnectyCube/connectycube-flutter-sdk-releases#97]
**Is your feature request related to a problem? Please describe.**
Most of the calling applications are required to provide status on the current call session's state i.e Connecting/Connected/Disconnected/Failed .. etc 

**Describe the solution you'd like**
A current call session state listener emitting events for the current initiated/accepted call

**Additional context**
This feature is available for all other platforms supported by connectycube, even if the first iteration would support IOS and Android would be huge progress forward for sdk users and would enable us to provide better solutions and experience for users

**Comment by TatankaConCube** [comment]
We will add this feature for P2P calls soon, in one of the near releases. Thank you for paying attention to it.

**Comment by TatankaConCube** [comment]
@AbdurrehmanSubhani additionali to [this callbacks](https://developers.connectycube.com/flutter/videocalling?id=add-listeners) you can add the `RTCSessionStateCallback` and listen the next events:
```dart
  void onConnectedToUser(T session, int userId);

  void onDisconnectedFromUser(T session, int userId);

  void onConnectionClosedForUser(T session, int userId);
```

for setting this callback use `callSession.setSessionCallbacksListener(listener)`

what other callbacks do you need?

**Comment by TatankaConCube** [comment]
the new version [2.10.0](https://pub.dev/packages/connectycube_sdk/changelog#2100) with the required functionality was published, and the [documentation](https://developers.connectycube.com/flutter/videocalling?id=monitor-session-connections-state) was updated

**Comment by AbdurrehmanSubhani** [comment]
Awesome, thanks! Really appreciate the quick response and the addition 🚀

**Comment by Wasif-Sadiq** [comment]
Awesome
