### ISSUE TITLE
Add minimum Android and iOS version support documentation

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [ConnectyCube/connectycube-flutter-sdk-releases#98]
Hey, I've been trying to find the minimum Android versions and iOS version support for the sdk but haven't been able to find any details regarding that, could you please specify the versions for both Android and iOS and add them the documentation as well for ease of developers

**Comment by TatankaConCube** [comment]
The minimum support version depends on the used features and the minimum versions of the dependencies' requirements. For now, for using all supported features the minimum version of Android is 21 (or 19 if the screen-sharing feature is not used in your app) and the iOS 12.0.
